apiVersion: v1
kind: Namespace
metadata:
  name: deploy-examples
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: deploy-examples
type: Opaque
stringData:
  DB_USER: "dbuser"
  DB_PASS: "s3cr3t"  # replace with real secret or use kubectl create secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment
  namespace: deploy-examples
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-app
  template:
    metadata:
      labels:
        app: secret-app
    spec:
      containers:
        - name: app
          image: busybox:1.36
          command: ["sh", "-c", "echo user=$DB_USER; echo pass=$DB_PASS; sleep 3600"]
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASS