apiVersion: v1
kind: Namespace
metadata:
  name: deploy-examples
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-sc
provisioner: placeholder.provisioner.io  # replace with cloud CSI (e.g., ebs.csi.aws.com)
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-claim
  namespace: deploy-examples
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: cloud-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-pvc-deployment
  namespace: deploy-examples
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
        - name: app
          image: busybox:1.36
          command: ["sh", "-c", "echo 'mounted cloud pvc' > /data/cloud.txt; sleep 3600"]
          volumeMounts:
            - name: cloud-vol
              mountPath: /data
      volumes:
        - name: cloud-vol
          persistentVolumeClaim:
            claimName: cloud-claim