apiVersion: v1
kind: Namespace
metadata:
  name: deploy-examples
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-app
  namespace: deploy-examples
spec:
  replicas: 2
  selector:
    matchLabels:
      app: autoscale
  template:
    metadata:
      labels:
        app: autoscale
    spec:
      containers:
        - name: app
          image: nginx:stable
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscale-app-hpa
  namespace: deploy-examples
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoscale-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: autoscale-pdb
  namespace: deploy-examples
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: autoscale