apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: web-stack
    role: frontend
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379
    volumeMounts:
    - name: shared-data
      mountPath: /data
  volumes:
  - name: shared-data
    emptyDir: {}  