apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: my-image:latest
        env:
        - name: MY_CONFIG
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: my-config-key

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  my-config-key: "This is a configuration value."